version: '3.7'

services:
  minesweeper-db:
    container_name: minesweeper-db
    image: library/mysql:8.0.22
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minesweeper
      MYSQL_USER: minesweeper
      MYSQL_PASSWORD: minesweeper
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306

  api:
    container_name: api
    build:
      context: ./minesweeper-API
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./minesweeper-API/:/usr/src/app/
    depends_on:
      - minesweeper-db
    links:
      - minesweeper-db
    ports:
      - 8000:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://minesweeper-db:3306/minesweeper
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  web:
    container_name: web
    stdin_open: true
    build:
      context: ./minesweeper-client
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - '/usr/src/app/node_modules'
      - './minesweeper-client:/usr/src/app'
