version: '3.7'

services:
  db:
    container_name: db
    image: library/mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=minesweeper
      - MYSQL_USER=minesweeper
      - MYSQL_PASSWORD=minesweeper
    ports:
      - 3306:3306

  api:
    container_name: api
    build: ./minesweeper-API
    command: java -jar /usr/src/app/target/minesweeper-0.0.1-SNAPSHOT.jar
    restart: on-failure
    volumes:
      - ./minesweeper-API/:/usr/src/app/
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/minesweeper?autoReconnect=true&useSSL=false

  web:
    container_name: web
    build:
      context: ./minesweeper-client
      dockerfile: Dockerfile
    volumes:
    - '.:/app'
    - '/app/node_modules'
    ports:
    - 3000:3000
    depends_on:
      - api
